### ISSUE TITLE
Help solve the memory problem make the library more optimized for work on the cpu? need to run without a video card

### ISSUE THREAD

**Issue by SyntaxEvg** [LM-Kit/lm-kit-net-samples#1] opened 2024-11-26 07:38 UTC
System.AccessViolationException: "Attempted to read or write protected memory. This is often an indication that other memory is corrupt."

![image](https://github.com/user-attachments/assets/052e92c9-f585-4237-a707-71bb7a1ea594)

**Comment by lcarrere** [comment] 2024-11-26 10:15
That's a very unexpected exception. Could you share a code snippet that allows us to replicate the issue? Additionally, we would need to know the model you're using.

**Comment by lcarrere** [comment] 2024-11-26 17:40
Is there any chance you could provide the stack trace of the exception?
Could you also confirm if you are using the latest release?
Any additional information would be helpful in diagnosing the issue.

**Comment by lcarrere** [comment] 2024-11-27 09:08
ok, thanks. Last couple of questions:

**1-** 

Does the error occur during the call to:

```
    _chatModel = new LLM(modelUri,
                           downloadingProgress: ModelDownloadingProgress,
                           loadingProgress: ModelLoadingProgress);
}
```

```
or:
_embeddingModel = new LLM(modelUri,
                       downloadingProgress: ModelDownloadingProgress)
```;

**2-**

Does the problem persists if you use:
```
            _chatModel = new LLM(modelUri,
                                 loadingOptions: new LLM.LoadingOptions() { LoadTensors = false },
                                 downloadingProgress: ModelDownloadingProgress,
                                 loadingProgress: ModelLoadingProgress);

//...

            _embeddingModel = new LLM(modelUri,
                                      loadingOptions: new LLM.LoadingOptions() { LoadTensors = false },
                                      downloadingProgress: ModelDownloadingProgress);
```

^ Note that I disabled tensor loading to test whether the segfault is caused by tensor parsing or vocab parsing. As a result, subsequent model usage will not work, which is expected at this stage.

**Comment by SyntaxEvg** [comment] 2024-11-29 15:17
_embeddingModel = new LLM(modelUri,downloadingProgress: ModelDownloadingProgress);
                                   "models\\lm-kit\\bge-1.5-gguf\\bge-small-en-v1.5-f16.gguf"

**Comment by SyntaxEvg** [comment] 2024-11-30 12:20
thanks, it worked, I'm studying the framework further

**Comment by lcarrere** [comment] 2024-11-30 14:28
Thanks for the return! I'm closing the issue right now.

**Closed by lcarrere** 2024-11-30 14:28 UTC
